spring:
  application:
    name: tickets-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tickets_db
    platform: POSTGRESQL
    username: ticket_app
    password: ticket_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



server:
  port: 8999
  servlet:
    context-path: /tickets
